from __future__ import annotations

import re
from pathlib import Path
from typing import Any


class CapabilityMapGenerator:
    """
    Builds a live map of services, tools, endpoints, persona files, memories, tests,
    and connected services.
    """

    def __init__(self, project_root: Path) -> None:
        self.project_root = project_root

    def generate_map(self) -> dict[str, Any]:
        tools = self._scan_tools()
        services = self._scan_services()
        endpoints = self._scan_endpoints()
        personas = self._scan_personas()
        tests = self._scan_tests()

        return {
            "ok": True,
            "project_name": "Vaila OS V3",
            "tools_count": len(tools),
            "services_count": len(services),
            "endpoints_count": len(endpoints),
            "personas_count": len(personas),
            "tests_count": len(tests),
            "tools": tools,
            "services": services,
            "endpoints": endpoints,
            "personas": personas,
            "tests": tests
        }

    def render_mermaid_flowchart(self) -> str:
        data = self.generate_map()
        
        lines = [
            "# Vaila OS V3 Capability & Architecture Map",
            "",
            "This document is auto-generated by the **CapabilityMapGenerator** tool. It maps the services, active persona filters, registered endpoints, tools, and corresponding test validation modules.",
            "",
            "## system flow diagram",
            "```mermaid",
            "graph TD",
            "  %% Node Styles",
            "  style CLIENT fill:#111827,stroke:#06b6d4,stroke-width:2px,color:#fff",
            "  style API fill:#1e1b4b,stroke:#8b5cf6,stroke-width:2px,color:#fff",
            "  style ROUTER fill:#0f172a,stroke:#3b82f6,stroke-width:2px,color:#fff",
            "  style ORCH fill:#022c22,stroke:#10b981,stroke-width:2px,color:#fff",
            "  style TOOLS fill:#312e81,stroke:#6366f1,stroke-width:2px,color:#fff",
            "  style PERS fill:#5c220f,stroke:#f59e0b,stroke-width:2px,color:#fff",
            "  style SERV fill:#172554,stroke:#3b82f6,stroke-width:1px,color:#fff",
            "",
            "  %% Subgraphs & Connections",
            "  subgraph Interface Layer",
            "    CLIENT[\"Vaila app.py<br>(CLI / Web GUI / Desktop Client)\"]",
            "  end",
            "",
            "  subgraph Gateway & Local API",
            "    API[\"local_api.py Fast API Server\"]",
            "  end",
            "",
            "  subgraph System Core Services",
            "    ROUTER[\"RouterService<br>(Task Regex Router)\"]",
            "    ORCH[\"OrchestrationService<br>(Llama/Gemini Gateway Orchestrator)\"]",
            "  end",
            "",
            "  CLIENT -->|REST API / WS| API",
            "  API -->|Envelope| ROUTER",
            "  ROUTER -->|Routed Route| ORCH",
            ""
        ]

        # Add active personas
        lines.append("  subgraph Persona Lenses")
        for persona in data["personas"]:
            lines.append(f"    PERS_{persona['id']}[\"Persona: {persona['name']}<br>({persona['tagline']})\"]")
            lines.append(f"    ORCH -->|Lens context| PERS_{persona['id']}")
        lines.append("  end")
        lines.append("")

        # Add registered tools
        lines.append("  subgraph System Tools Layer")
        for tool in data["tools"]:
            lines.append(f"    TOOL_{tool['id']}[\"Tool: {tool['name']}<br>({tool['file_name']})\"]")
            lines.append(f"    ORCH -->|Invoke tool| TOOL_{tool['id']}")
        lines.append("  end")
        lines.append("")

        # Add endpoints mapping to tools
        lines.append("  subgraph Registered Routes")
        for idx, endpoint in enumerate(data["endpoints"][:15]):  # limit lines for readability
            method = endpoint["method"]
            path = endpoint["path"]
            clean_path = path.replace("/", "_").replace("{", "").replace("}", "")
            lines.append(f"    EP_{clean_path}[\"{method} {path}\"]")
            lines.append(f"    API --> EP_{clean_path}")
        lines.append("  end")

        lines.append("```")
        lines.append("")
        lines.append("## 📦 Detailed System Component Catalog")
        
        # Tools Catalog
        lines.append("### 🛠️ registered system tools")
        for tool in data["tools"]:
            lines.append(f"- **{tool['name']}** (`{tool['module_path']}`): Detected executable class inside `{tool['file_name']}`.")

        # Services Catalog
        lines.append("")
        lines.append("### ⚙️ system core services")
        for service in data["services"]:
            lines.append(f"- **{service['class_name']}** (`{service['file_path']}`): Encapsulates core Vaila system utilities.")

        # Active Endpoints
        lines.append("")
        lines.append("### 🌐 API endpoints")
        for endpoint in data["endpoints"]:
            lines.append(f"- `{endpoint['method']}` `{endpoint['path']}`: Maps to handler `{endpoint['handler_name']}`.")

        # Validation Tests
        lines.append("")
        lines.append("### 🧪 unit validation test modules")
        for test in data["tests"]:
            lines.append(f"- `{test['file_name']}`: Validates functionality. Contains `{len(test['functions'])}` test functions.")

        return "\n".join(lines)

    def _scan_tools(self) -> list[dict[str, Any]]:
        tools = []
        tools_dir = self.project_root / "System_Tools"
        if not tools_dir.exists():
            return []

        for p in tools_dir.glob("*.py"):
            if p.stem == "__init__":
                continue
            
            content = p.read_text(encoding="utf-8", errors="replace")
            # Parse class name (e.g. class FileAnalyzer:)
            class_match = re.search(r"class\s+([A-Za-z0-9_]+)", content)
            class_name = class_match.group(1) if class_match else p.stem.title().replace("_", "")

            tools.append({
                "id": p.stem,
                "name": p.stem.replace("_", " ").title(),
                "file_name": p.name,
                "module_path": f"System_Tools.{p.stem}",
                "class_name": class_name
            })
        return tools

    def _scan_services(self) -> list[dict[str, Any]]:
        services = []
        services_dir = self.project_root / "System_Services"
        if not services_dir.exists():
            return []

        for p in services_dir.glob("*.py"):
            if p.stem == "__init__":
                continue

            content = p.read_text(encoding="utf-8", errors="replace")
            class_match = re.search(r"class\s+([A-Za-z0-9_]+)", content)
            class_name = class_match.group(1) if class_match else p.stem.title().replace("_", "")

            services.append({
                "id": p.stem,
                "class_name": class_name,
                "file_path": f"System_Services/{p.name}"
            })
        return services

    def _scan_endpoints(self) -> list[dict[str, Any]]:
        endpoints = []
        api_path = self.project_root / "Core_System_Files" / "local_api.py"
        if not api_path.exists():
            return []

        content = api_path.read_text(encoding="utf-8", errors="replace")
        
        # Look for router decorators, e.g. @app.get("/api/...") or @app.post("/chat")
        pattern = r"@app\.(get|post|put|delete|patch)\(\"([^\"]+)\"\)\n(?:async\s+)?def\s+([a-zA-Z0-9_]+)"
        matches = re.findall(pattern, content)
        for method, path, handler in matches:
            endpoints.append({
                "method": method.upper(),
                "path": path,
                "handler_name": handler
            })
        return endpoints

    def _scan_personas(self) -> list[dict[str, Any]]:
        # Hardcoded to match Vaila's actual persona configurations
        return [
            {"id": "proto_jane", "name": "Proto Jane", "tagline": "Default system Lens"},
            {"id": "serren", "name": "Serren", "tagline": "Cognitive empathy & growth"},
            {"id": "maelith", "name": "Maelith", "tagline": "Structural optimization"},
            {"id": "vecht", "name": "Vecht", "tagline": "Tactical immediate tasks"},
            {"id": "riven", "name": "Riven", "tagline": "Self-assessment & introspection"}
        ]

    def _scan_tests(self) -> list[dict[str, Any]]:
        tests = []
        tests_dir = self.project_root / "tests"
        if not tests_dir.exists():
            return []

        for p in tests_dir.glob("test_*.py"):
            content = p.read_text(encoding="utf-8", errors="replace")
            test_funcs = re.findall(r"def\s+(test_[a-zA-Z0-9_]+)", content)
            
            tests.append({
                "file_name": p.name,
                "functions": test_funcs
            })
        return tests
